call conda activate spark-lr;

python benchmark.py --core *  --input input/generated_files/1mb.csv
python benchmark.py --core 16 --input input/generated_files/1mb.csv
python benchmark.py --core 15 --input input/generated_files/1mb.csv
python benchmark.py --core 14 --input input/generated_files/1mb.csv
python benchmark.py --core 13 --input input/generated_files/1mb.csv
python benchmark.py --core 12 --input input/generated_files/1mb.csv
python benchmark.py --core 11 --input input/generated_files/1mb.csv
python benchmark.py --core 10 --input input/generated_files/1mb.csv
python benchmark.py --core 9  --input input/generated_files/1mb.csv
python benchmark.py --core 8  --input input/generated_files/1mb.csv
python benchmark.py --core 7  --input input/generated_files/1mb.csv
python benchmark.py --core 6  --input input/generated_files/1mb.csv
python benchmark.py --core 5  --input input/generated_files/1mb.csv
python benchmark.py --core 4  --input input/generated_files/1mb.csv
python benchmark.py --core 3  --input input/generated_files/1mb.csv
python benchmark.py --core 2  --input input/generated_files/1mb.csv
python benchmark.py --core 1  --input input/generated_files/1mb.csv

python benchmark.py --core *  --input input/generated_files/10mb.csv
python benchmark.py --core 16 --input input/generated_files/10mb.csv
python benchmark.py --core 15 --input input/generated_files/10mb.csv
python benchmark.py --core 14 --input input/generated_files/10mb.csv
python benchmark.py --core 13 --input input/generated_files/10mb.csv
python benchmark.py --core 12 --input input/generated_files/10mb.csv
python benchmark.py --core 11 --input input/generated_files/10mb.csv
python benchmark.py --core 10 --input input/generated_files/10mb.csv
python benchmark.py --core 9  --input input/generated_files/10mb.csv
python benchmark.py --core 8  --input input/generated_files/10mb.csv
python benchmark.py --core 7  --input input/generated_files/10mb.csv
python benchmark.py --core 6  --input input/generated_files/10mb.csv
python benchmark.py --core 5  --input input/generated_files/10mb.csv
python benchmark.py --core 4  --input input/generated_files/10mb.csv
python benchmark.py --core 3  --input input/generated_files/10mb.csv
python benchmark.py --core 2  --input input/generated_files/10mb.csv
python benchmark.py --core 1  --input input/generated_files/10mb.csv

python benchmark.py --core *  --input input/generated_files/100mb.csv
python benchmark.py --core 16 --input input/generated_files/100mb.csv
python benchmark.py --core 15 --input input/generated_files/100mb.csv
python benchmark.py --core 14 --input input/generated_files/100mb.csv
python benchmark.py --core 13 --input input/generated_files/100mb.csv
python benchmark.py --core 12 --input input/generated_files/100mb.csv
python benchmark.py --core 11 --input input/generated_files/100mb.csv
python benchmark.py --core 10 --input input/generated_files/100mb.csv
python benchmark.py --core 9  --input input/generated_files/100mb.csv
python benchmark.py --core 8  --input input/generated_files/100mb.csv
python benchmark.py --core 7  --input input/generated_files/100mb.csv
python benchmark.py --core 6  --input input/generated_files/100mb.csv
python benchmark.py --core 5  --input input/generated_files/100mb.csv
python benchmark.py --core 4  --input input/generated_files/100mb.csv
python benchmark.py --core 3  --input input/generated_files/100mb.csv
python benchmark.py --core 2  --input input/generated_files/100mb.csv
python benchmark.py --core 1  --input input/generated_files/100mb.csv

python benchmark.py --core *  --input input/generated_files/1000mb.csv
python benchmark.py --core 16 --input input/generated_files/1000mb.csv
python benchmark.py --core 15 --input input/generated_files/1000mb.csv
python benchmark.py --core 14 --input input/generated_files/1000mb.csv
python benchmark.py --core 13 --input input/generated_files/1000mb.csv
python benchmark.py --core 12 --input input/generated_files/1000mb.csv
python benchmark.py --core 11 --input input/generated_files/1000mb.csv
python benchmark.py --core 10 --input input/generated_files/1000mb.csv
python benchmark.py --core 9  --input input/generated_files/1000mb.csv
python benchmark.py --core 8  --input input/generated_files/1000mb.csv
python benchmark.py --core 7  --input input/generated_files/1000mb.csv
python benchmark.py --core 6  --input input/generated_files/1000mb.csv
python benchmark.py --core 5  --input input/generated_files/1000mb.csv
python benchmark.py --core 4  --input input/generated_files/1000mb.csv
python benchmark.py --core 3  --input input/generated_files/1000mb.csv
python benchmark.py --core 2  --input input/generated_files/1000mb.csv
python benchmark.py --core 1  --input input/generated_files/1000mb.csv

python benchmark.py --core *  --input input/generated_files/10000mb.csv
python benchmark.py --core 16 --input input/generated_files/10000mb.csv
python benchmark.py --core 15 --input input/generated_files/10000mb.csv
python benchmark.py --core 14 --input input/generated_files/10000mb.csv
python benchmark.py --core 13 --input input/generated_files/10000mb.csv
python benchmark.py --core 12 --input input/generated_files/10000mb.csv
python benchmark.py --core 11 --input input/generated_files/10000mb.csv
python benchmark.py --core 10 --input input/generated_files/10000mb.csv
python benchmark.py --core 9  --input input/generated_files/10000mb.csv
python benchmark.py --core 8  --input input/generated_files/10000mb.csv
python benchmark.py --core 7  --input input/generated_files/10000mb.csv
python benchmark.py --core 6  --input input/generated_files/10000mb.csv
python benchmark.py --core 5  --input input/generated_files/10000mb.csv
python benchmark.py --core 4  --input input/generated_files/10000mb.csv
python benchmark.py --core 3  --input input/generated_files/10000mb.csv
python benchmark.py --core 2  --input input/generated_files/10000mb.csv
python benchmark.py --core 1  --input input/generated_files/10000mb.csv
